/**
 * @description Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *
 * @param {number} number
 *
 * @returns {number} The sum of the even-valued terms in the Fibonacci sequence whose values do not exceed the provided parameter value number.
 */
const fiboEvenSum = (number) => {
  let sum = 0;
  let previous = 0;
  let current = 1;
  let next = 0;

  while (current <= number) {
    // If the current term is even, add it to the sum.
    if (current % 2 === 0) {
      sum = sum + current;
    }

    // The next term is the sum of the previous two terms.
    next = current + previous;
    previous = current;
    current = next;
  }

  return sum;
};

console.log(fiboEvenSum(10)); // 10
console.log(fiboEvenSum(4000000)); // 4613732
